"""Create the users table.

Adds user accounts for Milestone 1.2 (IAM-1). The table enforces the rules
that must hold even when a write bypasses the service: emails are unique and
stored lowercase, and roles are limited to the ``Role`` values. The three
account flags get database defaults, so rows inserted with raw SQL still get
safe values. Downgrading drops the table and every account in it.

Revision ID: feee06ced45e
Revises:
Create Date: 2026-09-24 22:51:46.241578

"""

# Type of down_revision, branch_labels, and depends_on.
from collections.abc import Sequence

# SQLAlchemy column and constraint types used in the table definition.
import sqlalchemy as sa

# Alembic operations that create and drop tables and indexes.
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "feee06ced45e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the users table, its constraints, and the staff filter index."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin",
                "receptionist",
                "nurse",
                "doctor",
                "pharmacist",
                "patient",
                "customer_service",
                "manager",
                name="role",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "must_change_password", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # A second email that differs only in case would pass the unique
        # constraint, so the database also rejects any non-lowercase email.
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index("ix_users_role_is_active", "users", ["role", "is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the staff filter index, then the users table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_role_is_active", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
